package ru.sber.smartapp.dsl.contract

import com.google.gson.GsonBuilder
import com.google.gson.JsonArray
import com.google.gson.JsonNull
import com.google.gson.JsonObject
import com.google.gson.JsonPrimitive
import java.io.File
import kotlin.system.exitProcess

/**
 * Экспортёр контракта данных в `shared/rules/rules.json`.
 *
 * Сериализует **те же** таблицы [SmartAppSpecs] / [TypeContextSpec] / [PathSpec] /
 * [FieldAccessSpec] / [JinjaSpec], которые использует рантайм плагина: своей копии
 * правил у экспортёра нет и быть не должно — иначе снимок разойдётся с поведением.
 *
 * Запуск: `exportRules [--check] <output-file>`.
 * Режим `--check` ничего не пишет, а сравнивает готовый снимок с файлом на диске и
 * завершается кодом 1 при расхождении (используется в CI).
 */
object ExportRules {

    @JvmStatic
    fun main(args: Array<String>) {
        val check = args.contains("--check")
        val outPath = args.firstOrNull { !it.startsWith("--") }
            ?: error("usage: exportRules [--check] <output-file>")
        val out = File(outPath)
        val rendered = render()

        if (!check) {
            out.parentFile?.mkdirs()
            out.writeText(rendered)
            println("Contract snapshot written to ${out.path}")
            return
        }

        val actual = if (out.isFile) out.readText() else null
        if (actual == rendered) {
            println("Contract snapshot is up to date: ${out.path}")
            return
        }
        System.err.println(
            if (actual == null) "Contract snapshot is missing: ${out.path}"
            else "Contract snapshot is stale: ${out.path}",
        )
        System.err.println("Run './gradlew :idea-plugin:exportRules' and commit the result.")
        exitProcess(1)
    }

    /** Детерминированный JSON-снимок контракта (стабильный порядок ключей). */
    fun render(): String {
        val root = JsonObject()
        root.add("_meta", meta())
        root.add("kinds", kinds())
        root.add("paths", paths())
        root.add("refRules", refRules())
        root.add("fileRefRules", fileRefRules())
        root.add("typeContext", typeContext())
        root.add("structuralKeys", strings(SmartAppSpecs.structuralKeys))
        root.add("fieldAccess", fieldAccess())
        root.add("jinja", jinja())
        root.add("keywordRegistries", stringMap(SmartAppSpecs.keywordRegistries))
        root.add("resourceScan", resourceScan())
        return GSON.toJson(root) + "\n"
    }

    private fun meta(): JsonObject = JsonObject().apply {
        addProperty("generated", true)
        addProperty("contractVersion", SmartAppContract.VERSION)
        addProperty(
            "note",
            "GENERATED by ':idea-plugin:exportRules' from Kotlin contract tables. Do not edit by hand.",
        )
    }

    private fun kinds(): JsonArray = JsonArray().apply {
        for (spec in SmartAppSpecs.kinds) {
            add(
                JsonObject().apply {
                    addProperty("kind", spec.kind.name)
                    addProperty("dirName", spec.dirName)
                },
            )
        }
    }

    private fun paths(): JsonObject = JsonObject().apply {
        add("rootSegments", strings(PathSpec.rootSegments))
        addProperty("fileExtension", PathSpec.fileExtension)
        addProperty("extensionIgnoreCase", PathSpec.extensionIgnoreCase)
    }

    private fun refRules(): JsonArray = JsonArray().apply {
        for (rule in SmartAppSpecs.refRules) {
            add(
                JsonObject().apply {
                    addProperty("property", rule.property)
                    // null означает «владелец не важен» / «любой вид файла» —
                    // пишем явный null, чтобы схема была строгой, а не «поле опущено».
                    add("ownerTypes", rule.ownerTypes?.let { strings(it) } ?: JsonNull.INSTANCE)
                    add(
                        "fileKind",
                        rule.fileKind?.let { JsonPrimitive(it.name) } ?: JsonNull.INSTANCE,
                    )
                    add("targets", strings(rule.targets.map { it.name }))
                },
            )
        }
    }

    private fun fileRefRules(): JsonArray = JsonArray().apply {
        for (rule in SmartAppSpecs.fileRefRules) {
            add(
                JsonObject().apply {
                    addProperty("property", rule.property)
                    add("ownerTypes", rule.ownerTypes?.let { strings(it) } ?: JsonNull.INSTANCE)
                    add("searchDirs", strings(rule.searchDirs))
                },
            )
        }
    }

    private fun typeContext(): JsonObject = JsonObject().apply {
        addProperty("typeProperty", TypeContextSpec.typeProperty)
        add("actionKeys", strings(TypeContextSpec.actionKeys))
        addProperty("actionCategory", TypeContextSpec.actionCategory)
        add("contextKeys", strings(TypeContextSpec.contextKeys))
        add("keyCategories", stringMap(TypeContextSpec.keyCategories))
        add("insideFieldsCategories", stringMap(TypeContextSpec.insideFieldsCategories))
        add(
            "fileKindCategory",
            JsonObject().apply {
                for ((kind, category) in TypeContextSpec.fileKindCategory) {
                    addProperty(kind.name, category)
                }
            },
        )
    }

    private fun resourceScan(): JsonObject = JsonObject().apply {
        addProperty("configFile", ResourceScanSpec.configFile)
        addProperty("resourcesVariable", ResourceScanSpec.resourcesVariable)
        addProperty("methodPrefix", ResourceScanSpec.methodPrefix)
        addProperty("fileExtension", ResourceScanSpec.fileExtension)
        addProperty("packageInitFile", ResourceScanSpec.packageInitFile)
        addProperty("maxBaseDepth", ResourceScanSpec.maxBaseDepth)
        add("excludedDirs", strings(ResourceScanSpec.excludedDirs))
    }

    private fun stringMap(values: Map<String, String>): JsonObject = JsonObject().apply {
        for ((key, value) in values) addProperty(key, value)
    }

    private fun fieldAccess(): JsonObject = JsonObject().apply {
        addProperty("formProperty", FieldAccessSpec.formProperty)
        addProperty("fieldsProperty", FieldAccessSpec.fieldsProperty)
    }

    private fun jinja(): JsonObject = JsonObject().apply {
        addProperty("formVariable", JinjaSpec.formVariable)
    }

    private fun strings(values: Iterable<String>): JsonArray =
        JsonArray().apply { values.forEach { add(it) } }

    // disableHtmlEscaping: снимок читают люди в code review, экранированные
    // апострофы (\u0027) только мешают.
    private val GSON = GsonBuilder()
        .setPrettyPrinting()
        .serializeNulls()
        .disableHtmlEscaping()
        .create()
}
